import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

const API = "http://127.0.0.1:8000";
const levels = ["low", "medium", "high"];
const List = ({ title, items }) => items?.length ? <section><h3>{title}</h3><ul>{items.map((item, i) => <li key={i}>{item}</li>)}</ul></section> : null;

export default function SkinAssessment() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ skin_type: "", acne_level: "", dryness_level: "", pigmentation_level: "", sensitivity_level: "", additional_concerns: "" });
  const [exists, setExists] = useState(false), [analysis, setAnalysis] = useState(null), [message, setMessage] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const token = localStorage.getItem("token");
  const auth = { Authorization: `Bearer ${token}` };

  useEffect(() => { fetch(`${API}/user/skin-assessment`, { headers: auth }).then(async r => ({ r, data: await r.json() })).then(({ r, data }) => { if (r.ok) { setForm({ skin_type: data.skin_type || "", acne_level: data.acne_level || "", dryness_level: data.dryness_level || "", pigmentation_level: data.pigmentation_level || "", sensitivity_level: data.sensitivity_level || "", additional_concerns: data.additional_concerns || "" }); setExists(true); } else if (r.status !== 404) setError(data.detail || "Unable to load assessment."); }).catch(() => setError("Unable to connect to backend.")); }, [token]);
  const change = e => setForm({ ...form, [e.target.name]: e.target.value });
  async function save(e) { e.preventDefault(); setSaving(true); setMessage(""); setError(""); try { const r = await fetch(`${API}/user/skin-assessment`, { method: exists ? "PUT" : "POST", headers: { ...auth, "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await r.json(); if (!r.ok) throw new Error(data.detail || "Unable to save assessment."); setExists(true); setMessage("Assessment saved. Analyze it to see personalized insights."); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function analyze() { setError(""); const r = await fetch(`${API}/user/skin-assessment/analysis`, { headers: auth }); const data = await r.json(); if (r.ok) setAnalysis(data); else setError(data.detail || "Unable to get skin analysis."); }

  return <div className="page"><header className="topbar"><div className="brand">Skin Intelligence</div><button className="small-btn" onClick={() => navigate("/dashboard")}>Dashboard</button></header><main className="dashboard"><h1>Skin Assessment</h1><p className="dashboard-subtitle">Receive explainable, personalized skincare guidance.</p><div className="card form-card"><form onSubmit={save}><div className="form-group"><label>Skin Type</label><select name="skin_type" value={form.skin_type} onChange={change} required><option value="">Select skin type</option>{["oily", "dry", "combination", "normal", "sensitive"].map(v => <option key={v}>{v}</option>)}</select></div>{[["acne_level", "Acne"], ["dryness_level", "Dryness"], ["pigmentation_level", "Pigmentation"], ["sensitivity_level", "Sensitivity"]].map(([name, label]) => <div className="form-group" key={name}><label>{label} Level</label><select name={name} value={form[name]} onChange={change}><option value="">Not specified</option>{levels.map(v => <option key={v}>{v}</option>)}</select></div>)}<div className="form-group"><label>Additional Concerns</label><textarea name="additional_concerns" value={form.additional_concerns} onChange={change} rows="4" /></div><button className="btn" disabled={saving}>{saving ? "Saving..." : exists ? "Update Assessment" : "Save Assessment"}</button></form>{message && <p className="message">{message}</p>}{error && <p className="message error">{error}</p>}<button className="small-btn" onClick={analyze} style={{ marginTop: 12 }}>Analyze My Skin</button><button className="small-btn" onClick={() => navigate("/routine")} style={{ margin: "12px 0 0 8px" }}>View Routine</button></div>{analysis && <div className="card"><h2>Your Skin Analysis</h2><p>Skin type: <strong>{analysis.skin_type}</strong></p>{analysis.concern_priorities?.length > 0 && <section><h3>Concern Priorities</h3><ul>{analysis.concern_priorities.map(item => <li key={item.concern}>{item.concern}: {item.severity} priority</li>)}</ul></section>}<List title="Skin Concerns" items={analysis.skin_concerns} /><List title="Risk Factors" items={analysis.risk_factors} /><List title="Lifestyle Insights" items={analysis.lifestyle_analysis} /><List title="Sleep Insights" items={analysis.sleep_analysis} /><List title="Environment Insights" items={analysis.environment_analysis} /><p className="message">{analysis.disclaimer}</p></div>}</main></div>;
}
